---
title: "Cocoa and Chocolates"
author: "G. AMANKWAH"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the Data into R
``` {r Loading CSV file}
library(readr)
library(tidyverse)
flavors_of_cacao <- read_csv("~/Downloads/Data Analysis with R programming/flavors_of_cacao.csv")
```

#Clean the data
``` {r overview of the data}
glimpse(flavors_of_cacao)

colnames(flavors_of_cacao)
```



``` {r rename selected variables}
flavors_of_cacao<- flavors_of_cacao %>%
  rename(Company = `Company 
(Maker-if known)`, com_location = `Company
Location`, Concentration = `Cocoa
Percent`)
```


```{r select key variales}
trimmed_flavors <- flavors_of_cacao %>%
  select (c(Rating, com_location, Concentration, Company))
```

``` {r }
as_tibble(trimmed_flavors)
```

# Summary of the data

``` {r }
trimmed_flavors %>%
  summarise(mean_ratings = mean(Rating), mean_Con= mean(Concentration), min_con = min(Concentration))
```


``` {r filtering the data}
best_trimmed_flavors_df <- trimmed_flavors %>%
  filter(Rating >= 3.9, Concentration >= 75)

as_tibble(best_trimmed_flavors_df)
```


# Visualization
``` {r bar graph}
ggplot(data = best_trimmed_flavors_df) + geom_bar (mapping = aes(x =com_location), , fill="red", color = "black")
```

``` {r categorizing the charts}
ggplot(data = best_trimmed_flavors_df) + geom_bar(mapping = aes(x = com_location)) + facet_wrap(~Company)
```


```{r adding labels}
ggplot(data = trimmed_flavors) + geom_point(mapping = aes(x = Concentration, y = Rating)) + labs (title ="Recommended Bars") 
```


